IMPERAS_HOME := $(shell getpath.exe "$(IMPERAS_HOME)")
CFLAGS=-I../../../../../ovpworld.org/modelSupport/psesockets/1.0/model
CFLAGS+=-I../../../plb/1.0/pse

include $(IMPERAS_HOME)/ImperasLib/buildutils/Makefile.pse
