/*
 * Copyright (c) 2005-2014 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef MICROBLAZE_MORPH_H
#define MICROBLAZE_MORPH_H

#include "vmi/vmiTypes.h"
#include "microblazeDecode.h"

#define MICROBLAZE_MORPH_FN(_NAME) void _NAME(microblazeMorphStateP state)
typedef MICROBLAZE_MORPH_FN((*microblazeMorphFn));

//
// Write Default Morpher stub Functions
//
MICROBLAZE_MORPH_FN(morphADD_TYPEA1);
MICROBLAZE_MORPH_FN(morphADDC_TYPEA1);
MICROBLAZE_MORPH_FN(morphADDK_TYPEA1);
MICROBLAZE_MORPH_FN(morphADDKC_TYPEA1);
MICROBLAZE_MORPH_FN(morphAND_TYPEA1);
MICROBLAZE_MORPH_FN(morphANDN_TYPEA1);
MICROBLAZE_MORPH_FN(morphFADD_TYPEA1);
MICROBLAZE_MORPH_FN(morphFCMPEQ_TYPEA1);
MICROBLAZE_MORPH_FN(morphFCMPGE_TYPEA1);
MICROBLAZE_MORPH_FN(morphFCMPGT_TYPEA1);
MICROBLAZE_MORPH_FN(morphFCMPLE_TYPEA1);
MICROBLAZE_MORPH_FN(morphFCMPLT_TYPEA1);
MICROBLAZE_MORPH_FN(morphFCMPNE_TYPEA1);
MICROBLAZE_MORPH_FN(morphFCMPUN_TYPEA1);
MICROBLAZE_MORPH_FN(morphFDIV_TYPEA1);
MICROBLAZE_MORPH_FN(morphFMUL_TYPEA1);
MICROBLAZE_MORPH_FN(morphFRSUB_TYPEA1);
MICROBLAZE_MORPH_FN(morphLWX_TYPEA1);
MICROBLAZE_MORPH_FN(morphMUL_TYPEA1);
MICROBLAZE_MORPH_FN(morphMULH_TYPEA1);
MICROBLAZE_MORPH_FN(morphMULHSU_TYPEA1);
MICROBLAZE_MORPH_FN(morphMULHU_TYPEA1);
MICROBLAZE_MORPH_FN(morphOR_TYPEA1);
MICROBLAZE_MORPH_FN(morphPCMPBF_TYPEA1);
MICROBLAZE_MORPH_FN(morphPCMPEQ_TYPEA1);
MICROBLAZE_MORPH_FN(morphPCMPNE_TYPEA1);
MICROBLAZE_MORPH_FN(morphRSUB_TYPEA1);
MICROBLAZE_MORPH_FN(morphRSUBC_TYPEA1);
MICROBLAZE_MORPH_FN(morphRSUBK_TYPEA1);
MICROBLAZE_MORPH_FN(morphRSUBKC_TYPEA1);
MICROBLAZE_MORPH_FN(morphSWX_TYPEA1);
MICROBLAZE_MORPH_FN(morphXOR_TYPEA1);
MICROBLAZE_MORPH_FN(morphBEQ_TYPEA2);
MICROBLAZE_MORPH_FN(morphBEQD_TYPEA2);
MICROBLAZE_MORPH_FN(morphBGE_TYPEA2);
MICROBLAZE_MORPH_FN(morphBGED_TYPEA2);
MICROBLAZE_MORPH_FN(morphBGT_TYPEA2);
MICROBLAZE_MORPH_FN(morphBGTD_TYPEA2);
MICROBLAZE_MORPH_FN(morphBLE_TYPEA2);
MICROBLAZE_MORPH_FN(morphBLED_TYPEA2);
MICROBLAZE_MORPH_FN(morphBLT_TYPEA2);
MICROBLAZE_MORPH_FN(morphBLTD_TYPEA2);
MICROBLAZE_MORPH_FN(morphBNE_TYPEA2);
MICROBLAZE_MORPH_FN(morphBNED_TYPEA2);
MICROBLAZE_MORPH_FN(morphBR_TYPEA3);
MICROBLAZE_MORPH_FN(morphBRA_TYPEA3);
MICROBLAZE_MORPH_FN(morphBRAD_TYPEA3);
MICROBLAZE_MORPH_FN(morphBRD_TYPEA3);
MICROBLAZE_MORPH_FN(morphBRALD_TYPEA4);
MICROBLAZE_MORPH_FN(morphBRLD_TYPEA4);
MICROBLAZE_MORPH_FN(morphBRK_TYPEA5);
MICROBLAZE_MORPH_FN(morphBSLL_TYPEA6);
MICROBLAZE_MORPH_FN(morphBSRA_TYPEA6);
MICROBLAZE_MORPH_FN(morphBSRL_TYPEA6);
MICROBLAZE_MORPH_FN(morphCMP_TYPEA7);
MICROBLAZE_MORPH_FN(morphCMPU_TYPEA7);
MICROBLAZE_MORPH_FN(morphIDIV_TYPEA7);
MICROBLAZE_MORPH_FN(morphIDIVU_TYPEA7);
MICROBLAZE_MORPH_FN(morphLBU_TYPEA8);
MICROBLAZE_MORPH_FN(morphLBUR_TYPEA8);
MICROBLAZE_MORPH_FN(morphLHU_TYPEA8);
MICROBLAZE_MORPH_FN(morphLHUR_TYPEA8);
MICROBLAZE_MORPH_FN(morphLW_TYPEA8);
MICROBLAZE_MORPH_FN(morphLWR_TYPEA8);
MICROBLAZE_MORPH_FN(morphSB_TYPEA8);
MICROBLAZE_MORPH_FN(morphSBR_TYPEA8);
MICROBLAZE_MORPH_FN(morphSH_TYPEA8);
MICROBLAZE_MORPH_FN(morphSHR_TYPEA8);
MICROBLAZE_MORPH_FN(morphSW_TYPEA8);
MICROBLAZE_MORPH_FN(morphSWR_TYPEA8);
MICROBLAZE_MORPH_FN(morphMFS_TYPEA9);
MICROBLAZE_MORPH_FN(morphMTS_TYPEAA);
MICROBLAZE_MORPH_FN(morphCLZ_TYPEAB);
MICROBLAZE_MORPH_FN(morphFINT_TYPEAB);
MICROBLAZE_MORPH_FN(morphFLT_TYPEAB);
MICROBLAZE_MORPH_FN(morphFSQRT_TYPEAB);
MICROBLAZE_MORPH_FN(morphSEXT16_TYPEAB);
MICROBLAZE_MORPH_FN(morphSEXT8_TYPEAB);
MICROBLAZE_MORPH_FN(morphSRA_TYPEAB);
MICROBLAZE_MORPH_FN(morphSRC_TYPEAB);
MICROBLAZE_MORPH_FN(morphSRL_TYPEAB);
MICROBLAZE_MORPH_FN(morphWDC_TYPEAC);
MICROBLAZE_MORPH_FN(morphWDCCLR_TYPEAC);
MICROBLAZE_MORPH_FN(morphWDCFL_TYPEAC);
MICROBLAZE_MORPH_FN(morphWIC_TYPEAC);
MICROBLAZE_MORPH_FN(morphADDI_TYPEB1);
MICROBLAZE_MORPH_FN(morphADDIC_TYPEB1);
MICROBLAZE_MORPH_FN(morphADDIK_TYPEB1);
MICROBLAZE_MORPH_FN(morphADDIKC_TYPEB1);
MICROBLAZE_MORPH_FN(morphANDI_TYPEB1);
MICROBLAZE_MORPH_FN(morphANDNI_TYPEB1);
MICROBLAZE_MORPH_FN(morphLBUI_TYPEB1);
MICROBLAZE_MORPH_FN(morphLHUI_TYPEB1);
MICROBLAZE_MORPH_FN(morphLWI_TYPEB1);
MICROBLAZE_MORPH_FN(morphMULI_TYPEB1);
MICROBLAZE_MORPH_FN(morphORI_TYPEB1);
MICROBLAZE_MORPH_FN(morphRSUBI_TYPEB1);
MICROBLAZE_MORPH_FN(morphRSUBIC_TYPEB1);
MICROBLAZE_MORPH_FN(morphRSUBIK_TYPEB1);
MICROBLAZE_MORPH_FN(morphRSUBIKC_TYPEB1);
MICROBLAZE_MORPH_FN(morphSBI_TYPEB1);
MICROBLAZE_MORPH_FN(morphSHI_TYPEB1);
MICROBLAZE_MORPH_FN(morphSWI_TYPEB1);
MICROBLAZE_MORPH_FN(morphXORI_TYPEB1);
MICROBLAZE_MORPH_FN(morphBEQI_TYPEB2);
MICROBLAZE_MORPH_FN(morphBEQID_TYPEB2);
MICROBLAZE_MORPH_FN(morphBGEI_TYPEB2);
MICROBLAZE_MORPH_FN(morphBGEID_TYPEB2);
MICROBLAZE_MORPH_FN(morphBGTI_TYPEB2);
MICROBLAZE_MORPH_FN(morphBGTID_TYPEB2);
MICROBLAZE_MORPH_FN(morphBLEI_TYPEB2);
MICROBLAZE_MORPH_FN(morphBLEID_TYPEB2);
MICROBLAZE_MORPH_FN(morphBLTI_TYPEB2);
MICROBLAZE_MORPH_FN(morphBLTID_TYPEB2);
MICROBLAZE_MORPH_FN(morphBNEI_TYPEB2);
MICROBLAZE_MORPH_FN(morphBNEID_TYPEB2);
MICROBLAZE_MORPH_FN(morphBRAI_TYPEB3);
MICROBLAZE_MORPH_FN(morphBRAID_TYPEB3);
MICROBLAZE_MORPH_FN(morphBRI_TYPEB3);
MICROBLAZE_MORPH_FN(morphBRID_TYPEB3);
MICROBLAZE_MORPH_FN(morphBRALID_TYPEB4);
MICROBLAZE_MORPH_FN(morphBRLID_TYPEB4);
MICROBLAZE_MORPH_FN(morphBRKI_TYPEB5);
MICROBLAZE_MORPH_FN(morphBSLLI_TYPEB6);
MICROBLAZE_MORPH_FN(morphBSRAI_TYPEB6);
MICROBLAZE_MORPH_FN(morphBSRLI_TYPEB6);
MICROBLAZE_MORPH_FN(morphMBAR_TYPEB8);
MICROBLAZE_MORPH_FN(morphMSRCLR_TYPEB9);
MICROBLAZE_MORPH_FN(morphMSRSET_TYPEB9);
MICROBLAZE_MORPH_FN(morphRTBD_TYPEBA);
MICROBLAZE_MORPH_FN(morphRTED_TYPEBA);
MICROBLAZE_MORPH_FN(morphRTID_TYPEBA);
MICROBLAZE_MORPH_FN(morphRTSD_TYPEBA);
MICROBLAZE_MORPH_FN(morphAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphCAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphCGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphEAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphECAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphECGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphEGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphNAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphNCAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphNCGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphNEAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphNECAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphNECGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphNEGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphNGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTCAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTCGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTEAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTECAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTECGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTEGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTNAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTNCAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTNCGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTNEAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTNECAGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTNECGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTNEGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphTNGET_TYPEC1);
MICROBLAZE_MORPH_FN(morphAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphCAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphCGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphEAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphECAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphECGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphEGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphNAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphNCAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphNCGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphNEAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphNECAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphNECGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphNEGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphNGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTCAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTCGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTEAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTECAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTECGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTEGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTNAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTNCAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTNCGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTNEAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTNECAGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTNECGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTNEGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphTNGETD_TYPEC2);
MICROBLAZE_MORPH_FN(morphAPUT_TYPEC3);
MICROBLAZE_MORPH_FN(morphCAPUT_TYPEC3);
MICROBLAZE_MORPH_FN(morphCPUT_TYPEC3);
MICROBLAZE_MORPH_FN(morphNAPUT_TYPEC3);
MICROBLAZE_MORPH_FN(morphNCAPUT_TYPEC3);
MICROBLAZE_MORPH_FN(morphNCPUT_TYPEC3);
MICROBLAZE_MORPH_FN(morphNPUT_TYPEC3);
MICROBLAZE_MORPH_FN(morphPUT_TYPEC3);
MICROBLAZE_MORPH_FN(morphAPUTD_TYPEC3D);
MICROBLAZE_MORPH_FN(morphCAPUTD_TYPEC3D);
MICROBLAZE_MORPH_FN(morphCPUTD_TYPEC3D);
MICROBLAZE_MORPH_FN(morphNAPUTD_TYPEC3D);
MICROBLAZE_MORPH_FN(morphNCAPUTD_TYPEC3D);
MICROBLAZE_MORPH_FN(morphNCPUTD_TYPEC3D);
MICROBLAZE_MORPH_FN(morphNPUTD_TYPEC3D);
MICROBLAZE_MORPH_FN(morphPUTD_TYPEC3D);
MICROBLAZE_MORPH_FN(morphTAPUT_TYPEC4);
MICROBLAZE_MORPH_FN(morphTCAPUT_TYPEC4);
MICROBLAZE_MORPH_FN(morphTCPUT_TYPEC4);
MICROBLAZE_MORPH_FN(morphTNAPUT_TYPEC4);
MICROBLAZE_MORPH_FN(morphTNCAPUT_TYPEC4);
MICROBLAZE_MORPH_FN(morphTNCPUT_TYPEC4);
MICROBLAZE_MORPH_FN(morphTNPUT_TYPEC4);
MICROBLAZE_MORPH_FN(morphTPUT_TYPEC4);
MICROBLAZE_MORPH_FN(morphTAPUTD_TYPEC4D);
MICROBLAZE_MORPH_FN(morphTCAPUTD_TYPEC4D);
MICROBLAZE_MORPH_FN(morphTCPUTD_TYPEC4D);
MICROBLAZE_MORPH_FN(morphTNAPUTD_TYPEC4D);
MICROBLAZE_MORPH_FN(morphTNCAPUTD_TYPEC4D);
MICROBLAZE_MORPH_FN(morphTNCPUTD_TYPEC4D);
MICROBLAZE_MORPH_FN(morphTNPUTD_TYPEC4D);
MICROBLAZE_MORPH_FN(morphTPUTD_TYPEC4D);
MICROBLAZE_MORPH_FN(morphIMM_TYPEI1);
MICROBLAZE_MORPH_FN(morphNOP_TYPEX);
typedef struct microblazeMorphAttrS {
    microblazeMorphFn morphCB; // callback function to morph the instruction
    microblazeArchitecture arch;
    vmiFlagsCP flags; // flags Constant pointer
} microblazeMorphAttr;

typedef struct microblazeMorphStateS {
    microblazeInstructionInfo info; // instruction description - from decoder
    microblazeMorphAttrCP attrs; // instruction attributes
    microblazeP microblaze; // current processor
    microblazeAddr nextPC; // next instruction address in sequence
} microblazeMorphState;

#endif // MICROBLAZE_MORPH_H
