/*
 * Copyright (c) 2005-2014 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef MICROBLAZE_DECODE_H
#define MICROBLAZE_DECODE_H

#include "hostapi/impTypes.h"
#include "microblazeStructure.h"

typedef enum microblazeInstructionTypeE {
    //
    // format TypeA1 Insns
    //
    MICROBLAZE_IT_ADD_TYPEA1,
    MICROBLAZE_IT_ADDC_TYPEA1,
    MICROBLAZE_IT_ADDK_TYPEA1,
    MICROBLAZE_IT_ADDKC_TYPEA1,
    MICROBLAZE_IT_AND_TYPEA1,
    MICROBLAZE_IT_ANDN_TYPEA1,
    MICROBLAZE_IT_FADD_TYPEA1,
    MICROBLAZE_IT_FCMPEQ_TYPEA1,
    MICROBLAZE_IT_FCMPGE_TYPEA1,
    MICROBLAZE_IT_FCMPGT_TYPEA1,
    MICROBLAZE_IT_FCMPLE_TYPEA1,
    MICROBLAZE_IT_FCMPLT_TYPEA1,
    MICROBLAZE_IT_FCMPNE_TYPEA1,
    MICROBLAZE_IT_FCMPUN_TYPEA1,
    MICROBLAZE_IT_FDIV_TYPEA1,
    MICROBLAZE_IT_FMUL_TYPEA1,
    MICROBLAZE_IT_FRSUB_TYPEA1,
    MICROBLAZE_IT_LWX_TYPEA1,
    MICROBLAZE_IT_MUL_TYPEA1,
    MICROBLAZE_IT_MULH_TYPEA1,
    MICROBLAZE_IT_MULHSU_TYPEA1,
    MICROBLAZE_IT_MULHU_TYPEA1,
    MICROBLAZE_IT_OR_TYPEA1,
    MICROBLAZE_IT_PCMPBF_TYPEA1,
    MICROBLAZE_IT_PCMPEQ_TYPEA1,
    MICROBLAZE_IT_PCMPNE_TYPEA1,
    MICROBLAZE_IT_RSUB_TYPEA1,
    MICROBLAZE_IT_RSUBC_TYPEA1,
    MICROBLAZE_IT_RSUBK_TYPEA1,
    MICROBLAZE_IT_RSUBKC_TYPEA1,
    MICROBLAZE_IT_SWX_TYPEA1,
    MICROBLAZE_IT_XOR_TYPEA1,

    //
    // format TypeA2 Insns
    //
    MICROBLAZE_IT_BEQ_TYPEA2,
    MICROBLAZE_IT_BEQD_TYPEA2,
    MICROBLAZE_IT_BGE_TYPEA2,
    MICROBLAZE_IT_BGED_TYPEA2,
    MICROBLAZE_IT_BGT_TYPEA2,
    MICROBLAZE_IT_BGTD_TYPEA2,
    MICROBLAZE_IT_BLE_TYPEA2,
    MICROBLAZE_IT_BLED_TYPEA2,
    MICROBLAZE_IT_BLT_TYPEA2,
    MICROBLAZE_IT_BLTD_TYPEA2,
    MICROBLAZE_IT_BNE_TYPEA2,
    MICROBLAZE_IT_BNED_TYPEA2,

    //
    // format TypeA3 Insns
    //
    MICROBLAZE_IT_BR_TYPEA3,
    MICROBLAZE_IT_BRA_TYPEA3,
    MICROBLAZE_IT_BRAD_TYPEA3,
    MICROBLAZE_IT_BRD_TYPEA3,

    //
    // format TypeA4 Insns
    //
    MICROBLAZE_IT_BRALD_TYPEA4,
    MICROBLAZE_IT_BRLD_TYPEA4,

    //
    // format TypeA5 Insns
    //
    MICROBLAZE_IT_BRK_TYPEA5,

    //
    // format TypeA6 Insns
    //
    MICROBLAZE_IT_BSLL_TYPEA6,
    MICROBLAZE_IT_BSRA_TYPEA6,
    MICROBLAZE_IT_BSRL_TYPEA6,

    //
    // format TypeA7 Insns
    //
    MICROBLAZE_IT_CMP_TYPEA7,
    MICROBLAZE_IT_CMPU_TYPEA7,
    MICROBLAZE_IT_IDIV_TYPEA7,
    MICROBLAZE_IT_IDIVU_TYPEA7,

    //
    // format TypeA8 Insns
    //
    MICROBLAZE_IT_LBU_TYPEA8,
    MICROBLAZE_IT_LBUR_TYPEA8,
    MICROBLAZE_IT_LHU_TYPEA8,
    MICROBLAZE_IT_LHUR_TYPEA8,
    MICROBLAZE_IT_LW_TYPEA8,
    MICROBLAZE_IT_LWR_TYPEA8,
    MICROBLAZE_IT_SB_TYPEA8,
    MICROBLAZE_IT_SBR_TYPEA8,
    MICROBLAZE_IT_SH_TYPEA8,
    MICROBLAZE_IT_SHR_TYPEA8,
    MICROBLAZE_IT_SW_TYPEA8,
    MICROBLAZE_IT_SWR_TYPEA8,

    //
    // format TypeA9 Insns
    //
    MICROBLAZE_IT_MFS_TYPEA9,

    //
    // format TypeAa Insns
    //
    MICROBLAZE_IT_MTS_TYPEAA,

    //
    // format TypeAb Insns
    //
    MICROBLAZE_IT_CLZ_TYPEAB,
    MICROBLAZE_IT_FINT_TYPEAB,
    MICROBLAZE_IT_FLT_TYPEAB,
    MICROBLAZE_IT_FSQRT_TYPEAB,
    MICROBLAZE_IT_SEXT16_TYPEAB,
    MICROBLAZE_IT_SEXT8_TYPEAB,
    MICROBLAZE_IT_SRA_TYPEAB,
    MICROBLAZE_IT_SRC_TYPEAB,
    MICROBLAZE_IT_SRL_TYPEAB,

    //
    // format TypeAc Insns
    //
    MICROBLAZE_IT_WDC_TYPEAC,
    MICROBLAZE_IT_WDCCLR_TYPEAC,
    MICROBLAZE_IT_WDCFL_TYPEAC,
    MICROBLAZE_IT_WIC_TYPEAC,

    //
    // format TypeB1 Insns
    //
    MICROBLAZE_IT_ADDI_TYPEB1,
    MICROBLAZE_IT_ADDIC_TYPEB1,
    MICROBLAZE_IT_ADDIK_TYPEB1,
    MICROBLAZE_IT_ADDIKC_TYPEB1,
    MICROBLAZE_IT_ANDI_TYPEB1,
    MICROBLAZE_IT_ANDNI_TYPEB1,
    MICROBLAZE_IT_LBUI_TYPEB1,
    MICROBLAZE_IT_LHUI_TYPEB1,
    MICROBLAZE_IT_LWI_TYPEB1,
    MICROBLAZE_IT_MULI_TYPEB1,
    MICROBLAZE_IT_ORI_TYPEB1,
    MICROBLAZE_IT_RSUBI_TYPEB1,
    MICROBLAZE_IT_RSUBIC_TYPEB1,
    MICROBLAZE_IT_RSUBIK_TYPEB1,
    MICROBLAZE_IT_RSUBIKC_TYPEB1,
    MICROBLAZE_IT_SBI_TYPEB1,
    MICROBLAZE_IT_SHI_TYPEB1,
    MICROBLAZE_IT_SWI_TYPEB1,
    MICROBLAZE_IT_XORI_TYPEB1,

    //
    // format TypeB2 Insns
    //
    MICROBLAZE_IT_BEQI_TYPEB2,
    MICROBLAZE_IT_BEQID_TYPEB2,
    MICROBLAZE_IT_BGEI_TYPEB2,
    MICROBLAZE_IT_BGEID_TYPEB2,
    MICROBLAZE_IT_BGTI_TYPEB2,
    MICROBLAZE_IT_BGTID_TYPEB2,
    MICROBLAZE_IT_BLEI_TYPEB2,
    MICROBLAZE_IT_BLEID_TYPEB2,
    MICROBLAZE_IT_BLTI_TYPEB2,
    MICROBLAZE_IT_BLTID_TYPEB2,
    MICROBLAZE_IT_BNEI_TYPEB2,
    MICROBLAZE_IT_BNEID_TYPEB2,

    //
    // format TypeB3 Insns
    //
    MICROBLAZE_IT_BRAI_TYPEB3,
    MICROBLAZE_IT_BRAID_TYPEB3,
    MICROBLAZE_IT_BRI_TYPEB3,
    MICROBLAZE_IT_BRID_TYPEB3,

    //
    // format TypeB4 Insns
    //
    MICROBLAZE_IT_BRALID_TYPEB4,
    MICROBLAZE_IT_BRLID_TYPEB4,

    //
    // format TypeB5 Insns
    //
    MICROBLAZE_IT_BRKI_TYPEB5,

    //
    // format TypeB6 Insns
    //
    MICROBLAZE_IT_BSLLI_TYPEB6,
    MICROBLAZE_IT_BSRAI_TYPEB6,
    MICROBLAZE_IT_BSRLI_TYPEB6,

    //
    // format TypeB8 Insns
    //
    MICROBLAZE_IT_MBAR_TYPEB8,

    //
    // format TypeB9 Insns
    //
    MICROBLAZE_IT_MSRCLR_TYPEB9,
    MICROBLAZE_IT_MSRSET_TYPEB9,

    //
    // format TypeBa Insns
    //
    MICROBLAZE_IT_RTBD_TYPEBA,
    MICROBLAZE_IT_RTED_TYPEBA,
    MICROBLAZE_IT_RTID_TYPEBA,
    MICROBLAZE_IT_RTSD_TYPEBA,

    //
    // format TypeC1 Insns
    //
    MICROBLAZE_IT_AGET_TYPEC1,
    MICROBLAZE_IT_CAGET_TYPEC1,
    MICROBLAZE_IT_CGET_TYPEC1,
    MICROBLAZE_IT_EAGET_TYPEC1,
    MICROBLAZE_IT_ECAGET_TYPEC1,
    MICROBLAZE_IT_ECGET_TYPEC1,
    MICROBLAZE_IT_EGET_TYPEC1,
    MICROBLAZE_IT_GET_TYPEC1,
    MICROBLAZE_IT_NAGET_TYPEC1,
    MICROBLAZE_IT_NCAGET_TYPEC1,
    MICROBLAZE_IT_NCGET_TYPEC1,
    MICROBLAZE_IT_NEAGET_TYPEC1,
    MICROBLAZE_IT_NECAGET_TYPEC1,
    MICROBLAZE_IT_NECGET_TYPEC1,
    MICROBLAZE_IT_NEGET_TYPEC1,
    MICROBLAZE_IT_NGET_TYPEC1,
    MICROBLAZE_IT_TAGET_TYPEC1,
    MICROBLAZE_IT_TCAGET_TYPEC1,
    MICROBLAZE_IT_TCGET_TYPEC1,
    MICROBLAZE_IT_TEAGET_TYPEC1,
    MICROBLAZE_IT_TECAGET_TYPEC1,
    MICROBLAZE_IT_TECGET_TYPEC1,
    MICROBLAZE_IT_TEGET_TYPEC1,
    MICROBLAZE_IT_TGET_TYPEC1,
    MICROBLAZE_IT_TNAGET_TYPEC1,
    MICROBLAZE_IT_TNCAGET_TYPEC1,
    MICROBLAZE_IT_TNCGET_TYPEC1,
    MICROBLAZE_IT_TNEAGET_TYPEC1,
    MICROBLAZE_IT_TNECAGET_TYPEC1,
    MICROBLAZE_IT_TNECGET_TYPEC1,
    MICROBLAZE_IT_TNEGET_TYPEC1,
    MICROBLAZE_IT_TNGET_TYPEC1,

    //
    // format TypeC2 Insns
    //
    MICROBLAZE_IT_AGETD_TYPEC2,
    MICROBLAZE_IT_CAGETD_TYPEC2,
    MICROBLAZE_IT_CGETD_TYPEC2,
    MICROBLAZE_IT_EAGETD_TYPEC2,
    MICROBLAZE_IT_ECAGETD_TYPEC2,
    MICROBLAZE_IT_ECGETD_TYPEC2,
    MICROBLAZE_IT_EGETD_TYPEC2,
    MICROBLAZE_IT_GETD_TYPEC2,
    MICROBLAZE_IT_NAGETD_TYPEC2,
    MICROBLAZE_IT_NCAGETD_TYPEC2,
    MICROBLAZE_IT_NCGETD_TYPEC2,
    MICROBLAZE_IT_NEAGETD_TYPEC2,
    MICROBLAZE_IT_NECAGETD_TYPEC2,
    MICROBLAZE_IT_NECGETD_TYPEC2,
    MICROBLAZE_IT_NEGETD_TYPEC2,
    MICROBLAZE_IT_NGETD_TYPEC2,
    MICROBLAZE_IT_TAGETD_TYPEC2,
    MICROBLAZE_IT_TCAGETD_TYPEC2,
    MICROBLAZE_IT_TCGETD_TYPEC2,
    MICROBLAZE_IT_TEAGETD_TYPEC2,
    MICROBLAZE_IT_TECAGETD_TYPEC2,
    MICROBLAZE_IT_TECGETD_TYPEC2,
    MICROBLAZE_IT_TEGETD_TYPEC2,
    MICROBLAZE_IT_TGETD_TYPEC2,
    MICROBLAZE_IT_TNAGETD_TYPEC2,
    MICROBLAZE_IT_TNCAGETD_TYPEC2,
    MICROBLAZE_IT_TNCGETD_TYPEC2,
    MICROBLAZE_IT_TNEAGETD_TYPEC2,
    MICROBLAZE_IT_TNECAGETD_TYPEC2,
    MICROBLAZE_IT_TNECGETD_TYPEC2,
    MICROBLAZE_IT_TNEGETD_TYPEC2,
    MICROBLAZE_IT_TNGETD_TYPEC2,

    //
    // format TypeC3 Insns
    //
    MICROBLAZE_IT_APUT_TYPEC3,
    MICROBLAZE_IT_CAPUT_TYPEC3,
    MICROBLAZE_IT_CPUT_TYPEC3,
    MICROBLAZE_IT_NAPUT_TYPEC3,
    MICROBLAZE_IT_NCAPUT_TYPEC3,
    MICROBLAZE_IT_NCPUT_TYPEC3,
    MICROBLAZE_IT_NPUT_TYPEC3,
    MICROBLAZE_IT_PUT_TYPEC3,

    //
    // format TypeC3d Insns
    //
    MICROBLAZE_IT_APUTD_TYPEC3D,
    MICROBLAZE_IT_CAPUTD_TYPEC3D,
    MICROBLAZE_IT_CPUTD_TYPEC3D,
    MICROBLAZE_IT_NAPUTD_TYPEC3D,
    MICROBLAZE_IT_NCAPUTD_TYPEC3D,
    MICROBLAZE_IT_NCPUTD_TYPEC3D,
    MICROBLAZE_IT_NPUTD_TYPEC3D,
    MICROBLAZE_IT_PUTD_TYPEC3D,

    //
    // format TypeC4 Insns
    //
    MICROBLAZE_IT_TAPUT_TYPEC4,
    MICROBLAZE_IT_TCAPUT_TYPEC4,
    MICROBLAZE_IT_TCPUT_TYPEC4,
    MICROBLAZE_IT_TNAPUT_TYPEC4,
    MICROBLAZE_IT_TNCAPUT_TYPEC4,
    MICROBLAZE_IT_TNCPUT_TYPEC4,
    MICROBLAZE_IT_TNPUT_TYPEC4,
    MICROBLAZE_IT_TPUT_TYPEC4,

    //
    // format TypeC4d Insns
    //
    MICROBLAZE_IT_TAPUTD_TYPEC4D,
    MICROBLAZE_IT_TCAPUTD_TYPEC4D,
    MICROBLAZE_IT_TCPUTD_TYPEC4D,
    MICROBLAZE_IT_TNAPUTD_TYPEC4D,
    MICROBLAZE_IT_TNCAPUTD_TYPEC4D,
    MICROBLAZE_IT_TNCPUTD_TYPEC4D,
    MICROBLAZE_IT_TNPUTD_TYPEC4D,
    MICROBLAZE_IT_TPUTD_TYPEC4D,

    //
    // format TypeI1 Insns
    //
    MICROBLAZE_IT_IMM_TYPEI1,

    //
    // format TypeX Insns
    //
    MICROBLAZE_IT_NOP_TYPEX,

    //
    // Drop through catch for instruction widths 32
    //
    MICROBLAZE_IT_INSTR32,

    //
    // Drop through catch all
    //
    MICROBLAZE_IT_LAST
} microblazeInstructionType;

#define MICROBLAZE_DISPATCH_FN(_NAME) void _NAME( \
    microblazeP microblaze, \
    microblazeInstructionInfoP info, \
    void *userData \
)

typedef MICROBLAZE_DISPATCH_FN((*microblazeDispatchFn));
typedef const microblazeDispatchFn microblazeDispatchTableC[MICROBLAZE_IT_LAST];
typedef microblazeDispatchTableC *microblazeDispatchTableCP;

vmidDecodeTableP microblazeCreateDecodeTable32(void);
void microblazeGenInstructionInfo (microblazeInstructionInfoP info, Uns64 instruction);

void microblazeDecode(
    microblazeP microblaze,
    microblazeAddr thisPC,
    microblazeInstructionInfoP info
);

//
// info structure accessed from decoder
//
typedef struct microblazeInstructionInfoS {
    //
    // Default structure members
    //
    const char *opcode;
    microblazeAddr thisPC;
    microblazeAddr nextPC;
    microblazeAddr branchPC;
    Uns32 instruction;
    Uns8  instrsize;
    microblazeInstructionType type;
    microblazeArchitecture arch;

    //
    // Instruction format generated structure members
    //
    Uns8 FSLx;
    Uns8 rA;
    Uns8 rB;
    Uns8 rD;
    Uns16 rS;
    Int16 simm;
    Int32 simmhi;
    Uns16 uimm;
} microblazeInstructionInfo;

#endif // MICROBLAZE_DECODE_H
